# docs: https://mmistakes.github.io/minimal-mistakes/docs/configuration/

# Site settings
minimal_mistakes_skin: default
locale: ko-KR
title: Input 보단 Output
email: funnycoding91@gmail.com
description: Java, Spring을 주로 다루는 백엔드 개발자 블로그
url: https://mskangg.github.io
github_username: mskangg
repository: mskangg/mskangg.github.io
search: true
words_per_minute: 200
breadcrumbs: false  # disabled by default 글 네비게이션

# Build settings
markdown: kramdown
remote_theme: mskangg/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# 댓글
comments:
  provider: utterances # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname: https-mskangg-github-io
  utterances:
    theme: github-light
    issue_term: pathname

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name   : "Life.play();"
  avatar : "/assets/images/my-profile.png"
  bio    : "클린 아키텍쳐와 코드 품질에 관심이 많은<br>개발자 강민수입니다."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mskangg"
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mskangg"
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"

# Site Default Post Settings
defaults:
  
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
